### ISSUE TITLE
Research how we can utilize local storage in Chrome profiles

### ISSUE THREAD

**Issue by shashjar** [shashjar/overgrown#3]
We will need to be able to locally store information about a given Chrome user who has the extension installed. This information includes (but is not necessarily limited to):
- Statistics on tabs
- Which plant they have chosen
- Any other user-customized settings they have access to

**Comment by breqdev** [comment]
hi @dillydally414 i like ur project its very cool

**Comment by dillydally414** [comment]
@breqdev stalker
